[build]
  command = "npm run build"
  publish = "dist"
  node_version = "20"

# SPA fallback (don’t swallow existing files like remoteEntry.js)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Light caching + CORS for remoteEntry.js (host will fetch cross-origin)
[[headers]]
  for = "/remoteEntry.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300, s-maxage=300"
    Cross-Origin-Resource-Policy = "cross-origin"

# Long cache for hashed assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
